name: E2E Tests
on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup docker and docker compose (missing on MacOS)
        if: runner.os == 'macos'
        run: |
          # see: https://github.com/actions/runner-images/issues/17#issuecomment-1537238473
          brew install docker
          colima start

          # For testcontainers to find the Colima socket
          # see: https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock

          # Install docker compose
          # see: https://zenn.dev/redgosho/articles/ee2bd023a946a2
          mkdir -p ~/.docker/cli-plugins/
          curl -SL https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-darwin-x86_64 -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose

      - name: Build Rust code
        run: docker compose up rust

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - run: npm install

      - run: xvfb-run -a npm test -w vsce
        if: runner.os == 'Linux'

      - run: npm test -w vsce
        if: runner.os != 'Linux'
